version: "3.6"

services:
    database:
        image: mariadb:latest
        environment:
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
            - MARIADB_DATABASE=karma8async
        volumes:
            - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
        restart: on-failure

    microservice:
        build:
            context: .
        environment:
            - DB_HOST=database
        depends_on:
            - database
        restart: on-failure
